@startuml
|User PC|
start
:Найти композицию;
if (Композиция найдена?) then (да)
  :Прослушать композицию;
else (нет)
  :Поиск не дал результатов;
endif
:Найти плейлист;
if (Плейлист найден?) then (да)
  :Прослушать плейлист;
else (нет)
  if (Плейлист должен быть создан?) then (да)
    :Создать плейлист;
  else (нет)
    :Поиск не дал результатов;
  endif
endif
:Найти плагин;
if (Плагин найден?) then (да)
  :Удалить плагин;
else (нет)
  :Поиск не дал результатов;
endif
:Найти плейлист;
if (Плейлист найден?) then (да)
  :Удалить плейлист;
else (нет)
  :Поиск не дал результатов;
endif
:Найти плейлист;
if (Плейлист найден?) then (да)
  :Изменить плейлист;
else (нет)
  :Поиск не дал результатов;
endif
stop
@enduml