@startuml
|User PC|
start

fork
  :Найти композицию;
  if (Композиция найдена?) then (да)
    :Прослушать композицию;
  else (нет)
    :Поиск не дал результатов;
  endif

fork again
  :Найти плейлист;
  if (Плейлист найден?) then (да)
    :Прослушать плейлист;
  else (нет)
    if (Плейлист должен быть создан?) then (да)
      :Создать плейлист;
    else (нет)
      :Поиск не дал результатов;
    endif
  endif


fork again
  :Найти плагин;
  if (Плагин найден?) then (да)
    :Удалить плагин;
  else (нет)
    :Поиск не дал результатов;
  endif
end fork

stop
@enduml